PROGS_MUTEX_SIMPLE_OBJS := mutex_simple.o
PROGS_MUTEX_SIMPLE_OBJS := $(PROGS_MUTEX_SIMPLE_OBJS:%=$(TDIR)/mutex_simple/%)
ALL_OBJS += $(PROGS_MUTEX_SIMPLE_OBJS)

$(TDIR)/bin/mutex_simple : $(TSTART) $(PROGS_MUTEX_SIMPLE_OBJS) $(TLIBC)

