PROGS_INVERSION_OBJS := inversion.o
PROGS_INVERSION_OBJS := $(PROGS_INVERSION_OBJS:%=$(TDIR)/inversion/%)
ALL_OBJS += $(PROGS_INVERSION_OBJS)

$(TDIR)/bin/inversion : $(TSTART) $(PROGS_INVERSION_OBJS) $(TLIBC)

