PROGS_MUTEX_NOUNLOCK_OBJS := mutex_nounlock.o
PROGS_MUTEX_NOUNLOCK_OBJS := $(PROGS_MUTEX_NOUNLOCK_OBJS:%=$(TDIR)/mutex_nounlock/%)
ALL_OBJS += $(PROGS_MUTEX_NOUNLOCK_OBJS)

$(TDIR)/bin/mutex_nounlock : $(TSTART) $(PROGS_MUTEX_NOUNLOCK_OBJS) $(TLIBC)

