PROGS_UBTEST_SUCCESS_OBJS := ubtest_success.o
PROGS_UBTEST_SUCCESS_OBJS := $(PROGS_UBTEST_SUCCESS_OBJS:%=$(TDIR)/ubtest_success/%)
ALL_OBJS += $(PROGS_UBTEST_SUCCESS_OBJS)

$(TDIR)/bin/ubtest_success : $(TSTART) $(PROGS_UBTEST_SUCCESS_OBJS) $(TLIBC)

