PROGS_DEV_MULTASK_OBJS := dev_multask.o
PROGS_DEV_MULTASK_OBJS := $(PROGS_DEV_MULTASK_OBJS:%=$(TDIR)/dev_multask/%)
ALL_OBJS += $(PROGS_DEV_MULTASK_OBJS)

$(TDIR)/bin/dev_multask : $(TSTART) $(PROGS_DEV_MULTASK_OBJS) $(TLIBC)

